/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as MeRouteImport } from './routes/me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripYourTripsRouteImport } from './routes/trip/your-trips'
import { Route as TripUpdateRouteImport } from './routes/trip/update'
import { Route as TripCreateRouteImport } from './routes/trip/create'
import { Route as TripTripIdRouteImport } from './routes/trip/$tripId'
import { Route as DestinationUpdateRouteImport } from './routes/destination/update'
import { Route as DestinationManageRouteImport } from './routes/destination/manage'
import { Route as DestinationCreateRouteImport } from './routes/destination/create'
import { Route as DestinationDestinationIdRouteImport } from './routes/destination/$destinationId'
import { Route as CategoryUpdateRouteImport } from './routes/category/update'
import { Route as CategoryManageRouteImport } from './routes/category/manage'
import { Route as CategoryCreateRouteImport } from './routes/category/create'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripYourTripsRoute = TripYourTripsRouteImport.update({
  id: '/trip/your-trips',
  path: '/trip/your-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const TripUpdateRoute = TripUpdateRouteImport.update({
  id: '/trip/update',
  path: '/trip/update',
  getParentRoute: () => rootRouteImport,
} as any)
const TripCreateRoute = TripCreateRouteImport.update({
  id: '/trip/create',
  path: '/trip/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TripTripIdRoute = TripTripIdRouteImport.update({
  id: '/trip/$tripId',
  path: '/trip/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationUpdateRoute = DestinationUpdateRouteImport.update({
  id: '/destination/update',
  path: '/destination/update',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationManageRoute = DestinationManageRouteImport.update({
  id: '/destination/manage',
  path: '/destination/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationCreateRoute = DestinationCreateRouteImport.update({
  id: '/destination/create',
  path: '/destination/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationDestinationIdRoute =
  DestinationDestinationIdRouteImport.update({
    id: '/destination/$destinationId',
    path: '/destination/$destinationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoryUpdateRoute = CategoryUpdateRouteImport.update({
  id: '/category/update',
  path: '/category/update',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryManageRoute = CategoryManageRouteImport.update({
  id: '/category/manage',
  path: '/category/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCreateRoute = CategoryCreateRouteImport.update({
  id: '/category/create',
  path: '/category/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/category/create': typeof CategoryCreateRoute
  '/category/manage': typeof CategoryManageRoute
  '/category/update': typeof CategoryUpdateRoute
  '/destination/$destinationId': typeof DestinationDestinationIdRoute
  '/destination/create': typeof DestinationCreateRoute
  '/destination/manage': typeof DestinationManageRoute
  '/destination/update': typeof DestinationUpdateRoute
  '/trip/$tripId': typeof TripTripIdRoute
  '/trip/create': typeof TripCreateRoute
  '/trip/update': typeof TripUpdateRoute
  '/trip/your-trips': typeof TripYourTripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/category/create': typeof CategoryCreateRoute
  '/category/manage': typeof CategoryManageRoute
  '/category/update': typeof CategoryUpdateRoute
  '/destination/$destinationId': typeof DestinationDestinationIdRoute
  '/destination/create': typeof DestinationCreateRoute
  '/destination/manage': typeof DestinationManageRoute
  '/destination/update': typeof DestinationUpdateRoute
  '/trip/$tripId': typeof TripTripIdRoute
  '/trip/create': typeof TripCreateRoute
  '/trip/update': typeof TripUpdateRoute
  '/trip/your-trips': typeof TripYourTripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/category/create': typeof CategoryCreateRoute
  '/category/manage': typeof CategoryManageRoute
  '/category/update': typeof CategoryUpdateRoute
  '/destination/$destinationId': typeof DestinationDestinationIdRoute
  '/destination/create': typeof DestinationCreateRoute
  '/destination/manage': typeof DestinationManageRoute
  '/destination/update': typeof DestinationUpdateRoute
  '/trip/$tripId': typeof TripTripIdRoute
  '/trip/create': typeof TripCreateRoute
  '/trip/update': typeof TripUpdateRoute
  '/trip/your-trips': typeof TripYourTripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/me'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/category/create'
    | '/category/manage'
    | '/category/update'
    | '/destination/$destinationId'
    | '/destination/create'
    | '/destination/manage'
    | '/destination/update'
    | '/trip/$tripId'
    | '/trip/create'
    | '/trip/update'
    | '/trip/your-trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/me'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/category/create'
    | '/category/manage'
    | '/category/update'
    | '/destination/$destinationId'
    | '/destination/create'
    | '/destination/manage'
    | '/destination/update'
    | '/trip/$tripId'
    | '/trip/create'
    | '/trip/update'
    | '/trip/your-trips'
  id:
    | '__root__'
    | '/'
    | '/me'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/category/create'
    | '/category/manage'
    | '/category/update'
    | '/destination/$destinationId'
    | '/destination/create'
    | '/destination/manage'
    | '/destination/update'
    | '/trip/$tripId'
    | '/trip/create'
    | '/trip/update'
    | '/trip/your-trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeRoute: typeof MeRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CategoryCreateRoute: typeof CategoryCreateRoute
  CategoryManageRoute: typeof CategoryManageRoute
  CategoryUpdateRoute: typeof CategoryUpdateRoute
  DestinationDestinationIdRoute: typeof DestinationDestinationIdRoute
  DestinationCreateRoute: typeof DestinationCreateRoute
  DestinationManageRoute: typeof DestinationManageRoute
  DestinationUpdateRoute: typeof DestinationUpdateRoute
  TripTripIdRoute: typeof TripTripIdRoute
  TripCreateRoute: typeof TripCreateRoute
  TripUpdateRoute: typeof TripUpdateRoute
  TripYourTripsRoute: typeof TripYourTripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/your-trips': {
      id: '/trip/your-trips'
      path: '/trip/your-trips'
      fullPath: '/trip/your-trips'
      preLoaderRoute: typeof TripYourTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/update': {
      id: '/trip/update'
      path: '/trip/update'
      fullPath: '/trip/update'
      preLoaderRoute: typeof TripUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/create': {
      id: '/trip/create'
      path: '/trip/create'
      fullPath: '/trip/create'
      preLoaderRoute: typeof TripCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$tripId': {
      id: '/trip/$tripId'
      path: '/trip/$tripId'
      fullPath: '/trip/$tripId'
      preLoaderRoute: typeof TripTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/update': {
      id: '/destination/update'
      path: '/destination/update'
      fullPath: '/destination/update'
      preLoaderRoute: typeof DestinationUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/manage': {
      id: '/destination/manage'
      path: '/destination/manage'
      fullPath: '/destination/manage'
      preLoaderRoute: typeof DestinationManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/create': {
      id: '/destination/create'
      path: '/destination/create'
      fullPath: '/destination/create'
      preLoaderRoute: typeof DestinationCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$destinationId': {
      id: '/destination/$destinationId'
      path: '/destination/$destinationId'
      fullPath: '/destination/$destinationId'
      preLoaderRoute: typeof DestinationDestinationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/update': {
      id: '/category/update'
      path: '/category/update'
      fullPath: '/category/update'
      preLoaderRoute: typeof CategoryUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/manage': {
      id: '/category/manage'
      path: '/category/manage'
      fullPath: '/category/manage'
      preLoaderRoute: typeof CategoryManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/create': {
      id: '/category/create'
      path: '/category/create'
      fullPath: '/category/create'
      preLoaderRoute: typeof CategoryCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeRoute: MeRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CategoryCreateRoute: CategoryCreateRoute,
  CategoryManageRoute: CategoryManageRoute,
  CategoryUpdateRoute: CategoryUpdateRoute,
  DestinationDestinationIdRoute: DestinationDestinationIdRoute,
  DestinationCreateRoute: DestinationCreateRoute,
  DestinationManageRoute: DestinationManageRoute,
  DestinationUpdateRoute: DestinationUpdateRoute,
  TripTripIdRoute: TripTripIdRoute,
  TripCreateRoute: TripCreateRoute,
  TripUpdateRoute: TripUpdateRoute,
  TripYourTripsRoute: TripYourTripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
